config/routes.rb
Balati::Application.routes.draw do

  match ':owner_type/:owner_id/activities' => 'activities#index'

  resources :activities

  resources :relationships
  
  resources :companies do
    resources :events, :only => [ :index, :new ]
    resources :activities, :only => [ :index ]
  end
  
  resources :rsvps, :only => [ :update ]
  
  resources :events, :except => [ :new ] do
    resources :rsvps, :only => [ :create ]
  end

  resources :users, :only => [ :show ] do
    resources :activities, :only => [ :index ]
    member do
      get :followers
      get :following
    end
  end

  resources :user_sessions, :only => :create

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  

  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  belongs_to :company
  has_many :entrances, :dependent => :delete_all
  has_many :rsvps, :dependent => :delete_all
  has_many :users, :through => :rsvps
  has_and_belongs_to_many :labels
  
  scope :attending, -> { includes{ rsvps }.where{ rsvps.status == 'attending' } }
  
  has_attached_file :cover,
    :styles => { :original => ['100%', :png], :small => ['480x100#', :png], :medium => ['767x200#', :png], :normal => ['980x300#', :png] },
    :storage => :s3,
    :whiny => false,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => "/event/cover/:style/:id.:extension"
  
  track_activity do |event, activity|
    activity.subject = event
    activity.owner = event.company
  end
  
  accepts_nested_attributes_for :entrances, :allow_destroy => true
  
  attr_accessible :company_id, :description, :name, :start_time, :entrances_attributes, :label_ids, :cover
  
  def rsvp(user)
    user ? rsvps.where(:user_id => user.id).first : nil
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticated
  
  # GET /events or /companies/1/events
  # GET /events.json or /companies/1/events.json
  def index
    @company = Company.includes(:events).find(params[:company_id]) if params.include? :company_id
    @events = @company.events unless @company.blank?
    if @events.blank?
      @events ||= Event.joins('LEFT JOIN events_labels el ON el.event_id = events.id').includes(:labels, :company).group('events.id')
      @events.order("SUM(CASE WHEN el.label_id IN (#{ current_user.label_ids.join "," }) THEN 1 ELSE 0 END) DESC") unless current_user.blank?
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.includes(:rsvps).where(:id => params[:id]).first
    
    @rsvp = @event.rsvps.where(:user_id => current_user.id).first if current_user
    @rsvp ||= Rsvp.new :event => @event
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /companies/1/events/new
  # GET /companies/1/events/new.json
  def new
    @event = Event.new
    @event.company = Company.find(params[:company_id])
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to company_events_url(@event.company) }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.haml
%article.event.event-resume
	%header.event-header.clearfix{ :style => "background-image: url(#{event.cover.url(:small)})" }
		%hgroup
			= link_to event do
				%h1.event-name= event.name
				%h2.event-company-name= event.company.name
		.event-header-buttons
			= render :partial => 'rsvps/button', :locals => { :rsvp => event.rsvp(current_user), :event => event }
			.event-friends-counter= "#{event.rsvps.attending.length} indo"
	.event-info
		%time.event-start-time
			%span.event-start-time-hour= event.start_time.strftime(event.start_time.min != 0 ? '%kh%M' : '%kh')
			%span.event-start-time-full-date
				%span.event-start-time-day-of-week= event.start_time.strftime('%A')
				%span.event-start-time-day= event.start_time.strftime('%e de %B')
		.event-friends-list.clearfix
			- event.rsvps.attending.each do |rsvp|
				= link_to rsvp.user do
					= image_tag rsvp.user.picture.url(:small_square), :class => 'event-friend'

app/views/events/_form.html.haml
= nested_form_for @event, :multipart => true do |f|
	- if @event.errors.any?
		#error_explanation
		%h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
		%ul
			- @event.errors.full_messages.each do |msg|
				%li= msg

	= f.hidden_field :company_id
	.field
		= f.label :name
		= f.text_field :name
	.field
		= f.label :cover
		= f.file_field :cover
	.field
		= f.label :description
		= f.text_area :description
	.field
		= f.label :start_time
		= f.datetime_select :start_time
	= f.fields_for :entrances do |entrance_form|	
		.field
			= entrance_form.label :price
			= entrance_form.number_field :price
		.field
			= entrance_form.label :description
			= entrance_form.text_field :description
		.field
			= entrance_form.label :order
			= entrance_form.number_field :order
		.field
			= entrance_form.link_to_remove "Remover"
	.field
		= f.link_to_add "Adicionar um preço", :entrances
	.field
		= f.label :labels
		= f.collection_select :label_ids, Label.all, :id, :name, {}, { :class => 'chzn-select', :multiple => 'multiple', :style => 'width: 350px;' }
	.actions
		= f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
= header "Events"

= render :partial => "event", :collection => @events

- unless @company.blank?
	= link_to 'New Event', new_company_event_path(@company)

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', @event.company

app/views/events/show.html.haml
= header @event.name, :back => root_url

%article.event
	%header.event-header.clearfix{ :style => "background-image: url(#{@event.cover.url(:small)})" }
		%hgroup
			= link_to @event.company do
				%h2.event-company-name= @event.company.name
				%h3.event-company-site= @event.company.site
		.event-header-buttons
			= render :partial => 'rsvps/button', :locals => { :rsvp => @event.rsvp(current_user), :event => @event }
			.event-friends-counter= "#{@event.rsvps.attending.length} indo"
	.event-info
		%time.event-start-time
			%span.event-start-time-hour= @event.start_time.strftime(@event.start_time.min != 0 ? '%kh%M' : '%kh')
			%span.event-start-time-full-date
				%span.event-start-time-day-of-week= @event.start_time.strftime('%A')
				%span.event-start-time-day= @event.start_time.strftime('%e de %B')
		%p.event-description
			= @event.description.chomp
		%p.event-location.clearfix
			= image_tag "http://maps.googleapis.com/maps/api/staticmap?markers=size:mid|color:red|#{@event.company.location.street}, #{@event.company.location.number}, #{@event.company.location.city}, #{@event.company.location.state}, #{@event.company.location.country}&size=60x60&sensor=false", :class => "event-location-map"
			= "#{@event.company.location.street}, #{@event.company.location.number}"
			%br
			= "#{@event.company.location.district}, #{@event.company.location.city} - #{@event.company.location.state}"
			%br
			= @event.company.phone
		.event-entrances
			%h2.event-entraces-title entrada (preços)
			%table.table.table-striped
				= render @event.entrances.ordered
		.event-rsvps
			%h2.event-rsvps-counter= pluralize @event.rsvps.attending.length, "confirmado", "confirmados"
			.event-rsvps-list.clearfix
				- @event.rsvps.attending.each do |rsvp|
					= link_to rsvp.user do
						= image_tag rsvp.user.picture.url(:small_square), :class => 'event-friend'