config/routes.rb
Balati::Application.routes.draw do

  match ':owner_type/:owner_id/activities' => 'activities#index'

  resources :activities

  resources :relationships
  
  resources :companies do
    resources :events, :only => [ :index, :new ]
    resources :activities, :only => [ :index ]
  end
  
  resources :rsvps, :only => [ :update ]
  
  resources :events, :except => [ :new ] do
    resources :rsvps, :only => [ :create ]
  end

  resources :users, :only => [ :show ] do
    resources :activities, :only => [ :index ]
    member do
      get :followers
      get :following
    end
  end

  resources :user_sessions, :only => :create

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  

  root :to => 'events#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  
  belongs_to :location
  has_many :events, :dependent => :delete_all
  has_many :activities, :as => :owner, :dependent => :delete_all
  has_many :relationships, :as => :follower, :dependent => :delete_all
  has_many :inverse_relationships, :class_name => "Relationship", :as => :following, :dependent => :delete_all
  has_many :pictures, :class_name => "CompanyPicture", :dependent => :delete_all
  
  attr_accessible :name, :phone, :location_attributes, :pictures_attributes, :site
  
  accepts_nested_attributes_for :location
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  
  def friends(user)
    company = self
    User.includes{ inverse_relationships }.includes{ rsvps.event.company }
      .where{ inverse_relationships.follower_id == user.id }
      .where{ inverse_relationships.follower_type == "User" }
      .where{ rsvps.event.company.id == company.id }
  end
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticated

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new
    @company.location = Location.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def render_pictures(pictures)
    carousel_id = "carousel-#{Time.now.to_i}"
    
    indicators = ""
    pictures.each_index do |i|
      indicators += content_tag :li, nil, :class => (i == 0 ? "active" : nil), :data => { :slide_to => i, :target => "##{carousel_id}" }
    end
    indicators = content_tag :ol, raw(indicators), :class => "carousel-indicators carousel-indicators-#{pictures.size}"
    
    inner = render(pictures)
    inner.gsub! "company-picture", "company-picture item"
    inner.sub! "item", "item active"
    inner = content_tag :div, raw(inner), :class => "carousel-inner"
    
    content_tag :div, indicators + inner, :class => "carousel slide company-pictures-carousel", :id => carousel_id, :data => { :interval => 5000, :auto => true }
  end
end

app/views/companies/_form.html.haml
= nested_form_for @company, :html => { :multipart => true } do |f|
	- if @company.errors.any?
		#error_explanation
		%h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
		%ul
			- @company.errors.full_messages.each do |msg|
				%li= msg

	.field
		= f.label :name
		= f.text_field :name
	.field
		= f.label :phone
		= f.text_field :phone
	= f.fields_for :location, @company.location do |location_fields|
		.field
			= location_fields.label :zip
			= location_fields.text_field :zip
		.field
			= location_fields.label :street
			= location_fields.text_field :street
		.field
			= location_fields.label :number
			= location_fields.text_field :number
		.field
			= location_fields.label :complement
			= location_fields.text_field :complement
		.field
			= location_fields.label :district
			= location_fields.text_field :district
		.field
			= location_fields.label :city
			= location_fields.text_field :city
		.field
			= location_fields.label :state
			= location_fields.text_field :state
		.field
			= location_fields.label :country
			= location_fields.text_field :country
	= f.fields_for :pictures do |picture_form|	
		.field
			= picture_form.label :image
			= picture_form.file_field :image
		.field
			= picture_form.link_to_remove "Remover"
	.field
		= f.link_to_add "Adicionar uma imagem", :pictures
	.actions
		= f.submit 'Save'

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h1 Listing companies

%table
	%tr
		%th Name
		%th Phone
		%th Location
		%th
		%th
		%th

	- @companies.each do |company|
		%tr
			%td= company.name
			%td= company.phone
			%td= company.location_id
			%td= link_to 'Show', company
			%td= link_to 'Edit', edit_company_path(company)
			%td= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }
			%td= link_to 'Events', company_events_path(company)
			%td= link_to 'Activities', company_activities_path(company)
		
%br

= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
= header "", :back => root_url

%article.company.clearfix
	%header.company-header.clearfix
		= render_pictures @company.pictures
		
	%h1.company-name= @company.name
	%p.company-location.clearfix
		= "#{@company.location.street}, #{@company.location.number}"
		%br
		= "#{@company.location.district}, #{@company.location.city} - #{@company.location.state}"
		%br
		= @company.phone
		%br
		= image_tag "http://maps.googleapis.com/maps/api/staticmap?markers=color:orange|#{@company.location.street}, #{@company.location.number}, #{@company.location.city}, #{@company.location.state}, #{@company.location.country}&size=400x150&sensor=false", :class => "company-location-map"

	.company-friends
		%h2.company-friends-counter= pluralize @company.friends(current_user).size, "amigo esteve aqui", "amigos estiveram aqui"
		.company-friends-list.clearfix
			- @company.friends(current_user).each do |user|
				= link_to user do
					= image_tag user.picture.url(:small_square), :class => 'company-friend'