config/routes.rb
Balati::Application.routes.draw do

  match ':owner_type/:owner_id/activities' => 'activities#index'

  resources :activities

  resources :relationships
  
  resources :companies do
    resources :events, :only => [ :index, :new ]
    resources :activities, :only => [ :index ]
  end
  
  resources :rsvps, :only => [ :update ]
  
  resources :events, :except => [ :new ] do
    resources :rsvps, :only => [ :create ]
  end

  resources :users, :only => [ :show ] do
    resources :activities, :only => [ :index ]
    member do
      get :followers
      get :following
    end
  end

  resources :user_sessions, :only => :create

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  

  root :to => 'events#index'

end

app/views/layouts/_menu.haml
%header.header-menu
	- if back
		= link_to '<', back, :class => 'header-menu-back'
	%h1.header-menu-title= title

app/views/layouts/application.html.haml
!!!5

/[if lt IE 7]
	<html class="no-js ie6 oldie">
/[if IE 7]
	<html class="no-js ie7 oldie">
/[if IE 8]
	<html class="no-js ie8 oldie">
\<!--[if gt IE 8]> -->
\	<html class="no-js">
\<!--<![endif]-->

%head
	%meta{ :charset => "utf-8" }
	= csrf_meta_tags

	/ Always force latest IE rendering engine (even in intranet) & Chrome Frame
	/ Remove this if you use the .htaccess
	%meta{ :http => { :equiv => "X-UA-Compatible" }, :content => "IE=edge,chrome=1" }

	%title Balati
	%meta{ :name => "description", :content => "" }
	%meta{ :name => "author", :content => "" }

	/ Mobile viewport optimized: j.mp/bplateviewport
	%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

	/ Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons
	= stylesheet_link_tag "application", :media => "all"

	/ All JavaScript at the bottom, except for Modernizr and Respond.
	/ Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
	= javascript_include_tag "modernizr"
%body
	= yield :header

	.content{ :class => "#{params[:controller]} #{params[:action]}" }
		= yield :sub_header
		= yield

	= yield :footer
	
	= javascript_include_tag "application"
	
	/ Segment.io (Analytics)
	- if Rails.env.production?
		:javascript
			var analytics=analytics||[];analytics.load=function(e){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+e+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);var r=function(e){return function(){analytics.push([e].concat(Array.prototype.slice.call(arguments,0)))}},i=["identify","track","trackLink","trackForm","trackClick","trackSubmit","pageview","ab","alias","ready"];for(var s=0;s<i.length;s++)analytics[i[s]]=r(i[s])};
			analytics.load("ucuvf1vlp4");
		- if current_user
			:javascript
				analytics.identify(#{current_user.id}, {
				    email: "#{current_user.email}",
				    name: "#{current_user.name}",
				    gender: "#{current_user.gender}"
				});

\</html>

app/views/layouts/main.html.haml
- content_for :footer do
	%nav.main-menu
		%li.main-menu-item
			= link_to current_user do
				%i.icon-user
				%br<>
				Perfil
		%li.main-menu-item
			= link_to root_path do
				%i.icon-home
				%br<>
				Home
		%li.main-menu-item
			= link_to user_path(current_user) do
				%i.icon-cogs
				%br<>
				Configurações

= render :template => 'layouts/application'

app/views/layouts/user.html.haml
= header @user.name, :back => root_url

- content_for :sub_header do
	%header.user-header.clearfix
		= image_tag @user.picture.url(:small_square), :class => "user-picture user-picture-50x50"
	
		= render :partial => 'relationships/follow', :locals => { :entity => @user }
	
		%nav.user-relationships.clearfix
			%li.user-followers-counter= link_to pluralize(@user.followers.length, "seguidor", "seguidores"), followers_user_path(@user)
			%li.user-following-counter= link_to pluralize(@user.following.length, "seguindo", "seguindo"), following_user_path(@user)

	%nav.user-menu.clearfix
		%li.user-menu-item Histórico
		%li.user-menu-item.user-menu-item-selected= link_to 'Festas', @user
		%li.user-menu-item= link_to 'Feed', user_activities_path(@user)

= render :template => 'layouts/main'